<?php
/**
 * @file
 * CSS3 Grid  - Responsive Fill and Fit columns
 */

/**
 * Implements hook_autoload_info.
 */
function views_grid_repeat_autoload_info() {
  return array(
    'views_plugin_style_views_grid_repeat' => 'views_plugin_style_views_grid_repeat.inc',
  );
}

/**
 * Implements hook_views_api()
 */
function views_grid_repeat_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'views_grid_repeat'),
    'template_path' => backdrop_get_path('module', 'views_grid_repeat'),
  );
}

/**
 * Preprocess function for views_view_views_grid_repeat.tpl.php.
 */
function template_preprocess_views_view_views_grid_repeat(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);
  // Get view options
 
  $view = $vars['view'];
  $options = $vars['options'];
  backdrop_set_message('<hr><br><pre>Template - $options<br>'. print_r($options, TRUE) .'</pre>'); 
}

/**
 * Implements hook_library_info().
 */
function views_grid_repeat_library_info() {
  $libraries = array();
  $libraries['views_grid_repeat'] = array(
    'title' => 'Views Grid Repeat',
    'version' => '1.0',
    'css' => array(
      backdrop_get_path('module', 'views_grid_repeat') . '/views_grid_repeat.css' => array(),
    ),
  );
   return $libraries;
}